### ISSUE TITLE
Save profile on Android app

### ISSUE THREAD

**Issue by slateroni** [ogarcia/rockpass#3]
Saving a new profile on Android lesspass app v9.7.2 to rockpass database fails. 
The app says "We cannot save your password profile".

syslog of the rockpass server says:
```
>> No 422 catcher registered. Using Rocket default.
>> Data guard `Json < NewPassword >` failed: Parse("{\"id\":null,\"site\":\"a\",\"login\":\"v\",\"lowercase\":true,\"uppercase\":true,\"number\":true,\"digits\":true,\"symbols\":true,\"length\":16,\"counter\":1}", Error("missing field `numbers`", line: 1, column: 135)).
```

Saving a new profile from the browser app works fine though. Otherwise the Android app works fine to read the database. 

I could fancy that this is *not* necessarily a rockpass issue. If so, please apologize.

**Comment by ogarcia** [comment]
As far as I can see it is a bug in the Android client that does not respect the model when sending a new password profile, it should send [`numbers`](https://github.com/ogarcia/rockpass/blob/master/src/models.rs#L85) (as do the extensions or the web client) and instead it sends `number`.

This could be solved in Rockpass by adding an [alias to serde](https://serde.rs/field-attrs.html#alias), but initially I am going to report it in LessPass because I understand that there should be consistency in the model.

**Comment by ogarcia** [comment]
@slateroni although the bug is from the Android clients that do not respect the model (and also omit the `version` field) when posting the password profile, I have created a [new version with a workaround](https://gitlab.com/ogarcia/rockpass/-/releases/0.9.0) to make it work correctly, as it is likely that @guillaumevincent needs more time to fix the problem in the mobile clients.

If you need to compile it for RPi 32bit you know:
```shell
git clone https://gitlab.com/ogarcia/rockpass.git # OR https://github.com/ogarcia/rockpass.git
cd rockpass
cargo build --release
```

Let me know if it worked correctly. :wink:

**Comment by slateroni** [comment]
yes, great. worked fine with v0.9.0. Thanks so much.
